batch_size: 128
bins:
- 0
- 50
- 200
- 1000
- 10000
checkpoint_path: ''
classify: true
device: 0
drug_featurizer: MorganFeaturizer,ChemBertaFeaturizer
drug_shape: 2048
ensemble_learn: false
experiment_id: bindingdb_mrogan_chembert_protbert_attetnion
latent_dimension: 1024
loss_type: OR
lr: 0.0001
lr_t0: 10
model_architecture: MorganChemBertaAttention
num_classes: 5
num_workers: 8
replicate: 0
shuffle: true
target_featurizer: ProtBertFeaturizer
target_shape: 1024
task: BindingDB
